/**
 * EXAMPLE / FALLBACK bodyHtml blocks for Dianetics Engine PSL sites.
 *
 * Status: pre–voice-pipeline commercial copy used by scripts/build-example-site.ts.
 * Production path: generate bodyHtml via content_agent.ts under
 * SA_CONTENT_RUNTIME_SYSTEM_PROMPT (docs/16, docs/17). Do not treat these
 * strings as the long-term voice standard — replace per-page with
 * voice-contract LLM output when running real Wave 1 builds.
 *
 * Constraints still observed here: non-medical, non-YMYL, soft Instant EFT CTA.
 */

export const PILLAR_BODY = `
<p>High-stakes decision makers in South Africa face a silent tax: residual mental noise that survives every strategy offsite and every wellness webinar. The classic 1950 text <em>Dianetics: The Modern Science of Mental Health</em> remains one of the most commercially durable self-improvement volumes ever printed precisely because it treats the mind as a practical instrument rather than a clinical mystery.</p>

<p>This site exists for one commercial purpose only — to put a physical hardcover of that book into the hands of executives, founders, and senior operators who prefer paper, quiet reading, and personal application over digital courses. No therapy claims. No process guarantees. Just the original literature, delivered by express courier within 24 hours of Instant EFT confirmation.</p>

<h2>Why physical still wins for executive clarity</h2>
<p>Screen fatigue is now a documented performance cost. Reading a structured book offline removes the notification layer and forces sequential attention. The 1950 framework inside Dianetics offers a vocabulary for locating and discharging reactive mental patterns that otherwise leak into board decisions, team dynamics, and personal recovery time. Readers use it as a private diagnostic tool, not as a substitute for professional care.</p>

<p>The edition we fulfil is the standard hardcover. Total landed cost is fixed at R400 (book + express courier). Payment is Instant EFT resolved to the nearest regional bank hub so funds and stock stay local. No foreign payment processors, no card data, no recurring subscriptions.</p>

<h2>How the regional fulfilment model works</h2>
<p>Four independent stock and dispatch nodes cover Gauteng, Western Cape, KwaZulu-Natal and Eastern Cape. Enter your suburb and city in the order form below; the system returns the matching bank details and a unique order reference (DIA-XXXXXX). Complete the Instant EFT with that exact reference, then confirm. The local hub receives an immediate dispatch alert and ships the same day or next morning under a 24-hour SLA target.</p>

<p>This is commercial book distribution, nothing more. The literature is sold for personal development reading. Any further application is the reader’s private responsibility.</p>

<p><strong>Ready to order?</strong> Complete the form in the Instant EFT section below. Your nearest hub and unique payment reference appear in seconds.</p>
`;

export const JOHANNESBURG_BODY = `
<p>Johannesburg and the broader Gauteng corridor generate the highest density of executive decision load in the country. Long hours, continuous context-switching, and residual mental static after the day ends are the norm rather than the exception. Many operators have already exhausted mindfulness apps and high-level coaching; they are looking for a durable, offline reference that can be re-read under pressure.</p>

<p>The 1950 volume <em>Dianetics: The Modern Science of Mental Health</em> continues to circulate among private readers for exactly this reason. It is sold here as commercial literature only — a physical hardcover for private study. No clinical claims are made. No group process is offered on this page.</p>

<h2>Gauteng fulfilment node</h2>
<p>Orders tagged to Randburg, Ferndale, Sandton, Midrand, Pretoria, Centurion, Fourways and surrounding suburbs resolve to the Gauteng Self-Mastery Publications hub (Standard Bank). Stock is held locally. After Instant EFT confirmation with your unique DIA- reference, the dispatch team aims to hand the package to express courier within the same business day. Target delivery window is 24 hours for major metro addresses.</p>

<p>The account holder name that appears on your bank statement is “Gauteng Self-Mastery Publications”. Use only the order reference generated by the form below; free-text payment notes are ignored by the matching system.</p>

<h2>Who this page serves</h2>
<p>Founders, partners, C-suite and senior managers who prefer a physical book they can annotate, leave on a desk, or pack for travel. The content is literary and historical. Application is entirely at the reader’s discretion. This site does not provide counselling, auditing invitations, or any form of therapeutic service.</p>

<p>Complete the Instant EFT form below to generate your regional bank details and order reference. Payment confirms the dispatch alert to the Randburg node.</p>
`;

export const CAPE_TOWN_BODY = `
<p>Cape Town operators frequently report a different texture of executive load: high creativity mixed with seasonal pressure spikes, long coastal commutes, and the constant background of lifestyle comparison. The residual mental noise is quieter than Johannesburg’s but just as persistent. A physical, non-digital reading protocol remains one of the few interventions that does not itself become another screen-based obligation.</p>

<p>We supply the original 1950 hardcover of <em>Dianetics: The Modern Science of Mental Health</em> as a commercial book sale. The text is offered for personal reading and private reflection only. It is not positioned as medical, psychological or religious instruction.</p>

<h2>Western Cape fulfilment</h2>
<p>Orders from Cape Town, Claremont, Observatory, Bellville, Stellenbosch, Somerset West, Milnerton and surrounding areas resolve to the Cape Town Dianetics Book Depot hub (FNB). Local stock and a dedicated dispatch email keep the 24-hour courier target realistic for the metro and immediate Winelands.</p>

<p>After you generate the Instant EFT details below, complete the transfer using the exact DIA- order reference. The confirmation button notifies the Observatory-area node so packaging can begin immediately.</p>

<h2>Practical use case</h2>
<p>Many readers keep the volume on a bedside or office shelf and return to specific sections when decision fatigue or interpersonal friction rises. The framework inside the book is sequential and self-contained. No external facilitator is required or offered through this commercial channel.</p>

<p>Use the form in the Instant EFT section to resolve your bank details and unique payment reference now.</p>
`;

export const DURBAN_BODY = `
<p>KwaZulu-Natal’s commercial centres — Durban, Umhlanga, Ballito, Pinetown — combine logistics intensity with a distinct coastal pace. Senior operators here often describe a particular form of residual stress: the mental residue of continuous operational firefighting that does not fully clear even after the weekend. Digital self-help content tends to blend into the same notification stream that created the load.</p>

<p>A physical copy of the 1950 classic <em>Dianetics: The Modern Science of Mental Health</em> is one of the few tools that forces a complete break from screens. We sell the hardcover as commercial literature for private reading. No therapeutic claims accompany the sale. No process invitations are extended on this page.</p>

<h2>KZN coastal fulfilment node</h2>
<p>Orders matching Durban, Umhlanga, Berea, Morningside, Westville, Ballito and nearby suburbs resolve to KZN Educational Literature (Nedbank). Stock is held in the Berea area. Instant EFT confirmation with the system-generated DIA- reference triggers an immediate alert to the local dispatch team. Express courier hand-over is targeted inside 24 hours for metro addresses.</p>

<p>The account name on your statement will read “KZN Educational Literature”. Always use the exact order reference shown after form submission.</p>

<h2>Positioning</h2>
<p>This is a book distribution page. The literature is historical and literary. Readers apply or set aside the material according to their own judgement. No further services are sold or implied here.</p>

<p>Generate your Instant EFT details and unique order reference with the form below.</p>
`;

export const GQEBERHA_BODY = `
<p>Gqeberha (Port Elizabeth) and the Eastern Cape commercial corridor operate under different constraints: longer supply lines, tighter specialist talent pools, and a higher personal cost when executive clarity slips. Operators here frequently seek durable, offline reference material that does not require another software login or monthly subscription.</p>

<p>The 1950 hardcover of <em>Dianetics: The Modern Science of Mental Health</em> continues to be ordered by private readers who want a structured, sequential self-improvement text they can mark up and revisit. We supply the physical book only. The sale is commercial and literary. No medical, clinical or process claims are made.</p>

<h2>Eastern Cape fulfilment</h2>
<p>Orders from Gqeberha, Port Elizabeth, Summerstrand, Newton Park, Uitenhage, East London and surrounding areas resolve to Eastern Cape Book Distribution (Absa). Local stock and a dedicated dispatch address keep the 24-hour express target achievable for the metro.</p>

<p>Complete the Instant EFT form below. The system returns the matching Absa account details and a unique DIA- order reference. Once the transfer is done, use the confirmation button so the Central Gqeberha node receives the packaging alert immediately.</p>

<h2>What you receive</h2>
<p>One physical hardcover of the original 1950 self-improvement volume, delivered by express courier. Total fixed price R400. Payment method is Instant EFT only. No card data is collected on this page. No recurring charges exist.</p>

<p>This page is a commercial book sales channel. Application of the literature remains the private responsibility of the reader.</p>

<p>Use the Instant EFT section now to generate your regional bank details and order reference.</p>
`;
